"""Augmente la taille du champ password

Revision ID: 15543caa981b
Revises: 0360f24cade9
Create Date: 2025-06-27 15:42:48.322867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15543caa981b'
down_revision = '0360f24cade9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
