"""Remove product_id from reviews

Revision ID: 415260e111d3
Revises: 6c350306a292
Create Date: 2025-06-30 16:11:14.565627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415260e111d3'
down_revision = '6c350306a292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('reviews_product_id_fkey', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
